### PR TITLE
Change the history with the anchor when selecting phase in startups dropdown

### PR DESCRIPTION
**Pull request by davidbgk**
Otherwise the `location.href` is updated then overridden by the change of history with the initial URL.

### CODE REVIEW

**Comment by Morendil** [comment]
I'm not sure I see what behaviour difference this makes. Would you mind outlining a test case?

**Comment by davidbgk** [comment]
> I'm not sure I see what behaviour difference this makes. Would you mind outlining a test case?

Sure, if you go to https://beta.gouv.fr/startups/ and choose an item from the dropdown (let's say Construction) you should go to that anchor *and* put it in the URL. For now, you are only moved to the right section of the page but the fragment is not put in the URL/history.

I realized that while trying to link to a section, I thought it was a bit overkill but then I read the code and it looked to be the initial implementation goal so I just had to fix it 👍

**Comment by Morendil** [comment]
Aaaah I get it - I wasn't looking at the dropdown at all, sorry.

This has some unexpected behaviour: if you pick several phases in a row, as the anchors accumulate at the end of the URL, i.e. you end up with for instance `https://deploy-preview-3482--beta-gouv-fr.netlify.com/startups/#acceleration#consolidation` which isn't a meaningful anchor.

I think you need to parse the URL, remove the existing anchor, and then append the new anchor to that.

The complexity is heading into "we need unit tests" territory - this page now has nearly as much JS code as it has lines of template code.

**Comment by davidbgk** [comment]
> This has some unexpected behaviour: if you pick several phases in a row, as the anchors accumulate at the end of the URL, i.e. you end up with for instance `https://deploy-preview-3482--beta-gouv-fr.netlify.com/startups/#acceleration#consolidation` which isn't a meaningful anchor.
> 
> I think you need to parse the URL, remove the existing anchor, and then append the new anchor to that.

Good catch, done!

> 
> The complexity is heading into "we need unit tests" territory - this page now has nearly as much JS code as it has lines of template code.

Agreed. Do we have anything in place for now?

**Pull request merged**
