### PR TITLE
harmonize ruby version and bump bundler

### PR DESCRIPTION
**Pull request by adipasquale**
I think it's important to make sure everyone is using the same ruby version. 
I used a `.ruby-version` file and set it to the latest version supported by Netlify 2.4.3 (cf [docs](https://www.netlify.com/docs/continuous-deployment/)). Note: I tried using 2.6.0 but it failed on Netlify on some obscure reasons, I think it's safer to stick to a supported version.

Currently, CircleCI defaults to 2.5.1 (cf [logs](https://circleci.com/gh/betagouv/beta.gouv.fr/1403?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)) while Netlify uses 2.3.6 (cf [logs](https://app.netlify.com/sites/beta-gouv-fr/deploys/5c3c9ca6103f890008a42854)).
This commit should therefore harmonize the ruby versions used locally, on the CI and in prod. 

I also updated the CONTRIBUTING instructions to suggest using RVM to isolate the environments. 
The instructions suggested using `production versions` but I'm not sure what it meant for ruby at least.
Jekyll's version should only be specified in the Gemfile imho.

Finally, running `bundle install` without any changes to the Gemfile gives a few minor updates to existing gems. 
They are mostly due to the bundler version bump, I don't think they should break anything in prod. 
I tested locally and it worked fine.

### CODE REVIEW

**Comment by adipasquale** [comment]
not exactly sure why the builds fail on Netlify and CircleCI. They both say `You must use Bundler 2 or greater with this lockfile.` but I don't know why they wouldn't use this version. Could someone try re-building without the cache on Netlify please ?

**Comment by jdauphant** [comment]
Ok, thanks, I will let @monbocal re-build without cache.
The current current image for circle-ci is "circleci/ruby:2.5.1-node-browsers", we should switch that too.

**Comment by monbocal** [comment]
Build failed even with a clear cache. I'm remembering something with ruby version and why I didn't specify it explicitely, but I'm not really sure why. I'm gonna try to jo my memory on this.

**Comment by adipasquale** [comment]
ok @monbocal and @jdauphant I'll try and figure out why it's failing on my side too. thanks for trying!

**Comment by monbocal** [comment]
The bundler's version bump is the main reason this is failing at the moment. It seems Netlify hasn't upgraded - yet : https://bundler.io/guides/bundler_2_upgrade.html .

**Comment by monbocal** [comment]
Yep, that's the thing : https://github.com/netlify/build-image/issues/250

**Comment by adipasquale** [comment]
oh ok I didn't realize that bundler 2 was so recent, I simply ran a full install of the project locally and got this new version. thanks for investigating. I guess we should just wait ~2 weeks or so and see if both Netlify and CircleCI up their game before trying to fix it in this project?

**Comment by monbocal** [comment]
Let's wait some time, yes :)

**Comment by adipasquale** [comment]
cool ! thanks for the followup

**Comment by monbocal** [comment]
> This is live now in both images. Use the newer versions of ruby to acquire bundler 2.

That happenned yesterday - tomorrow I'll look into it!

**Comment by adipasquale** [comment]
👍 thanks for your patience and followup !

**Pull request merged**
